version: '2'

services:
  mysql:
    image: mysql:8.0.14
    volumes:
    - "./docker/mysql/.data:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8090:80
    links:
      - mysql
    environment:
      - PMA_ARBITRARY=1

  php-fpm:
    build:
      context: docker/php-fpm
      args:
        TIMEZONE: ${TIMEZONE}
    environment:
      - PHP_IDE_CONFIG=serverName=project-server
    volumes:
    - ${CODE_PATH}:/var/www/code

  nginx:
    image: nginx:latest
    ports:
    - 8000:80
    links:
    - php-fpm
    volumes:
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./docker/nginx/logs/:/var/log/nginx
    - ${CODE_PATH}:/var/www/code
